name: Calendar Service workflow for FocusFlow

on:
  push:
    branches:
      - main
      - release
      - debug
      - test

jobs:
  create_meta_data:
    name: Создание мета-данных
    runs-on: ubuntu-latest

    outputs:
      image: ${{ steps.normalize.outputs.image_lc }}
      tag_sha: ${{ steps.set_meta.outputs.tag_sha }}

    steps:
      - name: Set meta data
        id: set_meta
        env: 
          OWNER: ${{ github.repository_owner }} 
          SHA: ${{ github.sha }}
        run: |
          echo "image=ghcr.io/${OWNER}/focusflow_calendar" >> $GITHUB_OUTPUT
          echo "tag_sha=${SHA}" >> $GITHUB_OUTPUT
          
      - name: Normalize image name
        id: normalize
        run: |
          IMAGE_LC=$(echo '${{ steps.set_meta.outputs.image }}' | tr '[:upper:]' '[:lower:]')
          echo "image_lc=$IMAGE_LC" >> $GITHUB_OUTPUT

  build_and_push_docker:
    name: Сборка и публикация Docker образа
    runs-on: ubuntu-latest
    needs: create_meta_data

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

        

      - name: Build Docker image
        run: docker build -t ${{ needs.create_meta_data.outputs.image }}:${{ needs.create_meta_data.outputs.tag_sha }} .

      - name: Push SHA tag
        run: docker push ${{ needs.create_meta_data.outputs.image }}:${{ needs.create_meta_data.outputs.tag_sha }}

  deploy_release_server:
    name: Деплой на сервер
    runs-on: ubuntu-latest
    needs: [build_and_push_docker, create_meta_data]

    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@v1.0.1
        with: 
          host: ${{ secrets.SERVER_RELEASE_HOST }}
          username: ${{ secrets.SERVER_RELEASE_USER }}
          key: ${{ secrets.SERVER_RELEASE_SSH_KEY }}
          port: ${{ secrets.SERVER_RELEASE_PORT }}
          script: |
            echo "Login GHCR..."
            echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ secrets.GHCR_USER }} --password-stdin

            IMAGE=${{ needs.create_meta_data.outputs.image }}
            TAG=${{ needs.create_meta_data.outputs.tag_sha }}

            docker pull ${IMAGE}:${TAG}

            echo "Stopping old container..."
            docker rm -f focusflow_calendar || true

            echo "Starting new container..."
            docker run -d \
              --name focusflow_calendar \
              --restart always \
              -p 8081:8080 \
              ${IMAGE}:${TAG}

              