name: Calendar Service workflow for FocusFlow

on:
  push:
    branches:
      - main
      - release
      - debug
      - test

jobs:
  build_and_push_docker:
    name: Сборка и публикация Docker образа
    runs-on: ubuntu-latest

    outputs:
      image: ${{ steps.normalize.outputs.image_lc }}
      tag_sha: ${{ steps.meta.outputs.TAG_SHA }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Meta (теги образа)
        id: meta
        run: |
          echo "IMAGE=ghcr.io/${{ github.repository_owner }}/focusflow_calendar" >> $GITHUB_OUTPUT
          echo "TAG_SHA=${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Normalize image name
        id: normalize
        run: |
          IMAGE_LC=$(echo '${{ steps.meta.outputs.IMAGE }}' | tr '[:upper:]' '[:lower:]')
          echo "image_lc=$IMAGE_LC" >> $GITHUB_OUTPUT
        

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_LC }}:${{ steps.meta.outputs.TAG_SHA }} .

      - name: Push SHA tag
        run: docker push ${{ env.IMAGE_LC }}:${{ steps.meta.outputs.TAG_SHA }}

  deploy_release_server:
    name: Деплой на сервер
    runs-on: ubuntu-latest
    needs: build_and_push_docker

    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.SERVER_RELEASE_HOST }}
          username: ${{ secrets.SERVER_RELEASE_USER }}
          key: ${{ secrets.SERVER_RELEASE_SSH_KEY }}
          port: ${{ secrets.SERVER_RELEASE_PORT }}
          script: |
            echo "Login GHCR..."
            echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ secrets.GHCR_USER }} --password-stdin

            IMAGE=${{ needs.build_and_push_docker.outputs.image }}
            TAG=${{ needs.build_and_push_docker.outputs.tag_sha }}

            docker pull ${IMAGE}:${TAG}

            echo "Stopping old container..."
            docker rm -f focusflow_calendar || true

            echo "Starting new container..."
            docker run -d \
              --name focusflow_calendar \
              --restart always \
              -p 8081:8080 \
              ${IMAGE}:${TAG}

              